# -*- coding: utf-8 -*-
<<<<<<< HEAD
from __future__ import unicode_literals

from django.db import models, migrations
=======
# Generated by Django 1.10.4 on 2016-11-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> chapter6


class Migration(migrations.Migration):

<<<<<<< HEAD
=======
    initial = True

>>>>>>> chapter6
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
            ],
            options={
            },
            bases=(models.Model,),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
>>>>>>> chapter6
        ),
    ]
