# -*- coding: utf-8 -*-
<<<<<<< HEAD
from __future__ import unicode_literals

from django.db import models, migrations
=======
# Generated by Django 1.10.4 on 2016-11-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> chapter6


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default=''),
<<<<<<< HEAD
            preserve_default=True,
=======
>>>>>>> chapter6
        ),
    ]
